{% set name = "pyvista-xarray" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyvista-xarray-{{ version }}.tar.gz
  sha256: 02e6359da75fc9dff55572b07b9eb46befd3f4168820bdf43438e7a8542d621d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - pyvista >=0.37
    - scooby
    - xarray >=2022.12.0

test:
  imports:
    - pvxarray
  commands:
    - pip check
    - python -c "import xarray; assert 'pyvista' in xarray.backends.list_engines()"
    - python -c "import pvxarray, xarray; da = xarray.DataArray(); assert hasattr(da, 'pyvista')"
  requires:
    - pip

about:
  home: https://github.com/pyvista/pyvista-xarray
  summary: PyVista DataArray accessors for xarray
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - banesullivan
