{% set name = "pyvista-xarray" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyvista-xarray-{{ version }}.tar.gz
  sha256: c25d555e27c6b9f2cda5a14feefb4cc3ba8f5b93f70f876779a0a5e0fded7651

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - pyvista >=0.37
    - scooby
    - xarray >=2022.12.0

test:
  imports:
    - pvxarray
  commands:
    - pip check
    - python -c "import xarray; assert 'pyvista' in xarray.backends.list_engines()"
    - python -c "import pvxarray, xarray; da = xarray.DataArray(); assert hasattr(da, 'pyvista')"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyvista/pyvista-xarray
  summary: PyVista DataArray accessors for xarray
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - banesullivan
